#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Algorithm-LCS
version:      1.04
version_from: LCS.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
